### ISSUE TITLE
Bug: M_FORBIDDEN: Failed to verify X-Matrix signatures.

### ISSUE THREAD

**Issue by slonkazoid** [girlbossceo/conduwuit#388]
conduit's [#256](https://gitlab.com/famedly/conduit/-/issues/256), which should have been fixed with [this change](https://gitlab.com/famedly/conduit/-/issues/256#note_1860812179), still happens on my instance

i tried creating a room with my matrix.org account, but it did not work. my client have me the error message `M_FORBIDDEN: Failed to verify X-Matrix signatures.`

here are the logs from conduwuit
```
2024-05-19T22:13:02.949887Z  INFO router:{path=/_matrix/client/r0/createRoom}:handle: conduit::api::client_server::room: @slonk:slonk.ing created a room with room ID !PLACEHOLDER-ROOM-ID:slonk.ing
2024-05-19T22:13:05.207866Z  INFO router:{path=/_matrix/client/r0/rooms/:room_id/messages}:handle:backfill_if_required{from=Normal(1017)}: conduit::service::rooms::timeline: Asking matrix.org for backfill
2024-05-19T22:13:05.441585Z  WARN router:{path=/_matrix/client/r0/rooms/:room_id/messages}:handle:backfill_if_required{from=Normal(1017)}: conduit::service::rooms::timeline: matrix.org failed to provide backfill for room !PLACEHOLDER-ROOM-ID:slonk.ing: matrix.org
2024-05-19T22:13:05.441737Z  INFO router:{path=/_matrix/client/r0/rooms/:room_id/messages}:handle:backfill_if_required{from=Normal(1017)}: conduit::service::rooms::timeline: No servers could backfill, but backfill was needed in room !PLACEHOLDER-ROOM-ID:slonk.ing
2024-05-19T22:13:19.223512Z  WARN router:{path=/_matrix/federation/v1/make_join/:room_id/:user_id}:handle: conduit::api::ruma_wrapper::axum: Failed to verify json request from matrix.org: Verification error: Could not verify signature: signature error: Verification equation was not satisfied
{"destination": String("slonk.ing"), "method": String("GET"), "origin": String("matrix.org"), "signatures": Object({"matrix.org": Object({"ed25519:a_RXGa": String("wXT8IKfLktlxKWI+f4DWEZ28t8bT/TAAQGAe/86gl08RdI0gs1qHYttpfhgOLpknTzNRJe3jeSj2fXJXL3IbAg")})}), "uri": String("/_matrix/federation/v1/make_join/!PLACEHOLDER-ROOM-ID:slonk.ing/@alifurkan:matrix.org?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6&ver=7&ver=8&ver=9&ver=10&ver=11")}
2024-05-19T22:13:19.223932Z  WARN router:{path=/_matrix/federation/v1/make_join/:room_id/:user_id}:handle: conduit::api::ruma_wrapper::axum: Request uri contained '@' character. Make sure your reverse proxy gives Conduit the raw uri (apache: use nocanon)
```
(i don't know how much info is sensitive, so i redacted the room id just in case)

i have delegation configured via reverse proxy & conduwuit.toml. i use lighttpd as my reverse proxy. i am running conduwuit v0.3.4 on aarch64-unknown-linux-musl. matrix.slonk.ing is not routed through cloudflare, but slonk.ing is, so unless lighttpd is messing with the URL, i don't see why this would happen

**Comment by slonkazoid** [comment]
when i try to create a room from matrix.org's side

before sending the first message
```
2024-05-19T22:46:50.324581Z  WARN router:{path=/_matrix/federation/v1/query/profile}:handle: conduit::api::ruma_wrapper::axum: Failed to verify json request from matrix.org: Verification error: Could not verify signature: signature error: Verification equation was not satisfied
{"destination": String("slonk.ing"), "method": String("GET"), "origin": String("matrix.org"), "signatures": Object({"matrix.org": Object({"ed25519:a_RXGa": String("DQEHL3WhbDcwavZgg8vCVAkZ4bLdarN+IV6cXFj5gG2xAt5AhhxGnKaBGVFJskU3CiZEm3QpQcMDj1Z5udlCAw")})}), "uri": String("/_matrix/federation/v1/query/profile?user_id=@slonk:slonk.ing&field=displayname")}
2024-05-19T22:46:50.324883Z  WARN router:{path=/_matrix/federation/v1/query/profile}:handle: conduit::api::ruma_wrapper::axum: Request uri contained '@' character. Make sure your reverse proxy gives Conduit the raw uri (apache: use nocanon)
```

after sending the first message
```
2024-05-19T22:47:03.862050Z  WARN router:{path=/_matrix/federation/v1/query/profile}:handle: conduit::api::ruma_wrapper::axum: Failed to verify json request from matrix.org: Verification error: Could not verify signature: signature error: Verification equation was not satisfied
{"destination": String("slonk.ing"), "method": String("GET"), "origin": String("matrix.org"), "signatures": Object({"matrix.org": Object({"ed25519:a_RXGa": String("DQEHL3WhbDcwavZgg8vCVAkZ4bLdarN+IV6cXFj5gG2xAt5AhhxGnKaBGVFJskU3CiZEm3QpQcMDj1Z5udlCAw")})}), "uri": String("/_matrix/federation/v1/query/profile?user_id=@slonk:slonk.ing&field=displayname")}
2024-05-19T22:47:03.862345Z  WARN router:{path=/_matrix/federation/v1/query/profile}:handle: conduit::api::ruma_wrapper::axum: Request uri contained '@' character. Make sure your reverse proxy gives Conduit the raw uri (apache: use nocanon)
2024-05-19T22:47:04.205105Z  WARN router:{path=/_matrix/federation/v2/invite/:room_id/:event_id}:handle: conduit::api::ruma_wrapper::axum: Failed to verify json request from matrix.org: Verification error: Could not verify signature: signature error: Verification equation was not satisfied
{"content": Object({"event": Object({"auth_events": Array([String("$fvhdax8nK6vAmDk0EhmRJYMm1qxS5vkzikCvPFzLK3A"), String("$tg9L5rEq7MGjWe8RTqyCr2iZz1jBUgxeY4XOgBfUXX4"), String("$1ePR6gerSc6l9GTg-WBEAA4UJO7CsCtFOr_UZt-eFOE"), String("$-t_95GO_Xc4M3q6a3E7FS1Y-CcXzc3Sc6GxrOMpEbTk")]), "content": Object({"is_direct": Bool(true), "membership": String("invite")}), "depth": 8, "hashes": Object({"sha256": String("lQwKjJF6+lqr+zxWjpXePaPQiaxtY4ZDg0sn9bvBmrE")}), "origin": String("matrix.org"), "origin_server_ts": 1716158823924, "prev_events": Array([String("$d6ccoFdb09hIYmJ9SByrOIC9DKhip1jAmHXb2-JwCNk")]), "room_id": String("!PLACEHOLDERER-ROOM-ID:matrix.org"), "sender": String("@alifurkan:matrix.org"), "signatures": Object({"matrix.org": Object({"ed25519:a_RXGa": String("rq0Q4Wb1d2isjL6uPYxAsVWn16J/kgnbQH7WRm32OX4atGGOE6mkNVC215PCjRXRbMLvlkMeABLeRgtvzk3OCg")})}), "state_key": String("@slonk:slonk.ing"), "type": String("m.room.member"), "unsigned": Object({"age": 32, "invite_room_state": Array([Object({"content": Object({"join_rule": String("invite")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.join_rules")}), Object({"content": Object({"algorithm": String("m.megolm.v1.aes-sha2")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.encryption")}), Object({"content": Object({"creator": String("@alifurkan:matrix.org"), "room_version": String("10")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.create")}), Object({"content": Object({"avatar_url": String("mxc://matrix.org/HLSOcyIhAhYSwsIBNjhbeTAU"), "displayname": String("migrated to @slonk:slonk.ing"), "membership": String("join")}), "sender": String("@alifurkan:matrix.org"), "state_key": String("@alifurkan:matrix.org"), "type": String("m.room.member")})])})}), "invite_room_state": Array([Object({"content": Object({"join_rule": String("invite")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.join_rules")}), Object({"content": Object({"algorithm": String("m.megolm.v1.aes-sha2")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.encryption")}), Object({"content": Object({"creator": String("@alifurkan:matrix.org"), "room_version": String("10")}), "sender": String("@alifurkan:matrix.org"), "state_key": String(""), "type": String("m.room.create")}), Object({"content": Object({"avatar_url": String("mxc://matrix.org/HLSOcyIhAhYSwsIBNjhbeTAU"), "displayname": String("migrated to @slonk:slonk.ing"), "membership": String("join")}), "sender": String("@alifurkan:matrix.org"), "state_key": String("@alifurkan:matrix.org"), "type": String("m.room.member")})]), "room_version": String("10")}), "destination": String("slonk.ing"), "method": String("PUT"), "origin": String("matrix.org"), "signatures": Object({"matrix.org": Object({"ed25519:a_RXGa": String("V1rDc8qoQvDs2fhOLndxgzJxHNjloT7xngwLyORSmWyTVzh2Bd1EUHw7c8e5k8e8obmPPVlHgyltCKXIAKyGBw")})}), "uri": String("/_matrix/federation/v2/invite/!PLACEHOLDERER-ROOM-ID:matrix.org/$I-DONT-WANT-TO-RISK-IT")}
```

**Comment by girlbossceo** [comment]
This seems to be a lighttpd configuration issue, I believe it's messing with the `Authorization` header with the X-Matrix map.

I'm not sure if Synapse does something to handle this (seems like no one runs Synapse with lighttpd anyways), and maybe ruma's WIP X-Matrix header parser might have something for this, but you need to possibly use something from here for the headers: https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails

> conduit's [#256](https://gitlab.com/famedly/conduit/-/issues/256), which should have been fixed with [this change](https://gitlab.com/famedly/conduit/-/issues/256#note_1860812179), still happens on my instance

For the record: Conduit has chosen to not merge that for some reason, and it was primarily intended to fix Complement/Sytest. There was no evidence it affected normal federation activity for users behind reverse proxies.

**Comment by slonkazoid** [comment]
> This seems to be a lighttpd configuration issue, I believe it's messing with the `Authorization` header with the X-Matrix map.

Yeah I set up caddy as a layer before lighttpd and made conduwuit route through that instead and it worked first try

> but you need to possibly use something from here for the headers: https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails

Nope, not even setting everything to `disable` worked, I guess lighttpd is just not compatible with conduit, not without extra work

I don't think this is a condu/wuit issue, but maybe a warning could be added to the documentation for this?

**Comment by girlbossceo** [comment]
I can add one, but as far as I can tell lighttpd isn't really a recommended reverse proxy in general compared to things like Caddy and nginx for complex applications like Matrix homeservers. Synapse doesn't mention anything about it.

**Comment by slonkazoid** [comment]
lighttpd itself isn't much popular, but I know at least 1 other person that might have suffered from this, so you never know

I don't know if I should close this now

**Comment by girlbossceo** [comment]
If you just decided to move to Caddy then it's resolved. I'll find a place to put in a "lighttpd is not supported" in the deploying docs.

**Comment by gstrauss** [comment]
@slonkazoid would you capture the request headers sent from the reverse proxy to the backend?  I'd like to see the difference between what caddy or nginx is sending to the backend versus what lighttpd is sending to the backend.

> Failed to verify json request from matrix.org: Verification error: Could not verify signature: signature error: Verification equation was not satisfied

is probably due to some difference in the request that is forwarded.

**Comment by slonkazoid** [comment]
dont have the setup right now and would take a while to set up

maybe today, maybe in the following weeks

**Comment by gstrauss** [comment]
@slonkazoid when you can.  thank you.  I am a lighttpd developer and am watching this thread.

**Comment by girlbossceo** [comment]
@gstrauss So for context, after I re-read this issue again; Matrix federation validates server signatures using the `Authorization` header, and instead of the type being `Bearer` or something, it's `X-Matrix` and the contents of the header are key-value pairs, and the request body is a large blurb of JSON.

Here is what an example minimal request would look like:

Request URI: `/_matrix/federation/v1/test?query=param`

Header:
`Authorization: X-Matrix origin="puppygock.gay",key="ed25519:awawawaw",sig="superlongbase64encodedsignature",destination="girlboss.ceo"`

Request POST body:
```json
{
    "method": "POST",
    "uri": "/_matrix/federation/v1/test?query=param",
    "origin": "puppygock.gay",
    "destination": "girlboss.ceo",
    "content": <super long JSON body here of a matrix request body, but its not relevant>,
    "signatures": {
        "puppygock.gay": {
            "ed25519:awawawaw": "superlongbase64encodedsignature"
        }
    }
}
```

When X-Matrix signatures fail to validate, sometimes it can be because conduwuit is not being given the original/non-canonicalised body and URI.

Nginx and Caddy seem to do this already on its own, but on Apache you need to use the `nocanon` mod_proxy option, so no "URL safe canonicalisation" or anything happens before.

I suspect this is the same issue Lighttpd has, but we tried to find the equivalent of Apache's `nocanon` reverse proxy option and we couldn't find anything.

Basically, I think Lighttpd is passing a request URI of `/_matrix/federation/v1/test%3Fquery%3Dparam` instead of `/_matrix/federation/v1/test?query=param` to conduwuit, which won't pass X-Matrix signature validation because those are treated as completely different `"uri":`'s. I can understand why this is being done, since it's a security measure of reducing the chance of maliciously crafted URIs to impact a vulnerable backend that can't handle unsafe URIs properly, but with Matrix it needs the full/raw original URI.

I don't have any logs or anything to give, but I'm pretty confident that this is the issue. If you know of any config option or something that we're missing to allow Lighttpd to pass the full/raw URI to the reverse proxy backend, that would be a good thing for us to try. 

I appreciate you chiming in and expressing interest in getting the issue fixed in Lighttpd.

**Comment by gstrauss** [comment]
If I could see the headers sent in client request and then those sent to backend in a good request versus an invalid request, I think that whatever the issue is will be apparent.

Enabled by default since lighttpd 1.4.54, lighttpd normalizes URLs.  This can be controlled (or disabled) with
lighttpd.conf [server.http-parseopts](https://wiki.lighttpd.net/Server_http-parseoptsDetails)

Temporarily disabling normalization might be useful for testing.  However, lighttpd developers strongly recommend for security that normalization be enabled.  If Matrix is passing URLs which are overly %-encoded or improperly %-encoded, then it might be better and more portable to adjust Matrix to perform the precise *necessary* %-encoding on the URL.

lighttpd mod_auth takes pains to implement HTTP Digest authentication where the URI might change due to url-rewriting.  As you noted, if the URL changes, X-Matrix validation will fail, as expected.

---

Separately -- and less likely to be the issue here -- [lighttpd mod_proxy](https://wiki.lighttpd.net/mod_proxy) has options in `proxy.header` directive for mapping Host and URL-path, though if you do not configure them, then lighttpd should send to the backend what was sent by the client.  Sometimes the mapping is needed when a path prefix (e.g. /websockets/) in the front-facing server needs to be removed for the request to the backend.
