### ISSUE TITLE
Is native sliding sync still experimental?

### ISSUE THREAD

**Issue by nisbet-hubbard** [girlbossceo/conduwuit#532]
I don’t see an entry for the required JSON in the example config:
```json
    "org.matrix.msc3575.proxy": {
        "url": "https://matrix.example.com"
    }
```
But the sliding sync does work when I put this in the client .well-known file.

Does this mean that native sliding sync is still experimental like in Synapse? And is there a timeline for when we should switch from the reference implementation?

**Comment by girlbossceo** [comment]
> I don’t see an entry for the required JSON in the example config:

This is because it's advertised when you configure the client well-known. I could probably make that more clear.

Either way though, native sliding sync is still experimental, but Element team is currently rewriting the entirety of the sliding sync MSC which has a high chance at breaking Conduit/conduwuit's implementation.

> is there a timeline for when we should switch from the reference implementation?

Whenever the sliding sync MSC is rewritten and Element X is rewritten to use the new implementation.
