### ISSUE TITLE
The Dockerfile should be in the repository

### ISSUE THREAD

**Issue by herzenschein** [girlbossceo/conduwuit#573]
I'm trying to:

* figure out why conduwuit does not run on my Raspberry Pi 4B despite the image being arm64 enabled (core dump)
* figure out how to turn it into a podman quadlet (so far it works fine on amd64)
* investigate possible outdated documentation or non-functional variables (CONDUWUIT_ALLOW_CHECK_FOR_UPDATES=false doesn't work for example)

But I cannot find the Dockerfile (or Containerfile) used to generate the container image. Contrary to what is done in other projects, the Dockerfile doesn't seem to be in the repo. Is it possibly being autogenerated, like in https://github.com/girlbossceo/conduwuit/blob/main/nix/pkgs/oci-image/default.nix?

**Comment by girlbossceo** [comment]
> figure out why conduwuit does not run on my Raspberry Pi 4B despite the image being arm64 enabled (core dump)

We had the target CPU bumped slightly too high, and I have a patch to fix it but I haven't merged it yet. I'll just push the commit though since it's been brought up a couple times and I still have stuff going on in my PR.

> figure out how to turn it into a podman quadlet (so far it works fine on amd64)

I'm not sure what this means, I recommend joining #conduwuit:puppygock.gay for more direct conversations with others about this who most likely know better about containers.

> investigate possible outdated documentation or non-functional variables (CONDUWUIT_ALLOW_CHECK_FOR_UPDATES=false doesn't work for example)

This config option accidentally lost in a major refactor a while ago, and will be fixed. This config option is disabled by default anyways and there is no outdated documentation.

>  Contrary to what is done in other projects, the Dockerfile doesn't seem to be in the repo. Is it possibly being autogenerated,

This is intended. We use Nix to auto-generate OCI images that get distributed across our multiple container registries, and a direct tarball if desired. The flake file you found is basically the definition for the OCI images (entrypoint, etc).

**Comment by girlbossceo** [comment]
I'm going to consider this resolved unless you have any further questions/concerns, which I think we'd be happy to answer better in `#conduwuit:puppygock.gay`

A fix for the target CPU issue has been pushed to the main branch, and `CONDUWUIT_ALLOW_CHECK_FOR_UPDATES` now works again. If you'd like to use it immediately use the artifacts from the [main CI workflow ](https://github.com/girlbossceo/conduwuit/actions/runs/10875974517)or the `main` Docker tag when the workflow finishes.
