### ISSUE TITLE
Add Docker CI

### ISSUE THREAD

**Issue by kubo6472** [girlbossceo/conduwuit#91]
Docker image building and pushing to ghcr support would be amazing.

**Comment by girlbossceo** [comment]
Could you try using the existing Nix infrastructure where possible? I recommend looking at how Nix CI/CD was done here:

https://github.com/girlbossceo/conduwuit/pull/8
https://charles.page.computer.surgery/engage/

If there are issues with how the Nix CI/CD infrastructure is setup/works that make outputting artifacts not possible, then it can be brought up to @CobaltCause

**Comment by kubo6472** [comment]
I will try, however no guarantees. I prefer testing with the structure of the CI I am familiar with, and then I have no problem of rapid-fixing the Nix based schema.

**Comment by girlbossceo** [comment]
Currently working on porting the upstream GitLab CI, which builds OCI images to use for Docker, to GitHub Actions (https://github.com/girlbossceo/conduwuit/issues/117)

**Comment by girlbossceo** [comment]
Still missing publishing to GitHub Container registry and Docker, and I would like to add additional targets like `x86_64-unknown-linux-musl-sha256-media` so it builds with the `sha256_media` feature but I'm so burnt out from this nix CI stuff so I'll maybe deal with it another time.

All artifacts outputted only have default features. I don't think many people are using sha256_media anyways except for me.

I was also left with no choice but to revert back to latest stable rust-rocksdb because of incredibly frustrating linker issues, but considering they said they would release a new version soon (https://github.com/rust-rocksdb/rust-rocksdb/issues/858#issuecomment-1918976791) I think this is fine as a temporary thing.

As is, it should be working the same as upstream and should be good enough.

**Comment by girlbossceo** [comment]
Docker images can now be pulled from:

https://hub.docker.com/repository/docker/girlbossceo/conduwuit/general

https://github.com/girlbossceo/conduwuit/pkgs/container/conduwuit
